### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by newcherryberry** [liutaocode/DiffDub#2]
Hi Liuta, 
So sorry if this is a bad repo to do this on, but I cannot find another way to contact you! I need some help with a project you have worked on before (OpenAnimate). Please let me know if I can email you or if you feel more comfortable emailing me.
Thanks,
Maylin

**Comment by liutaocode** [comment]
Hello, I haven't continued my work on OpenAnimate recently. If you have any questions, feel free to email me at: liutaw@sjtu.edu.cn
